version: '3'
services:
  web:
    environment:
      DJANGO_SECRET_KEY: (Replace with your secret key)
      DJANGO_DEBUG: 'False'
      DJANGO_ALLOWED_HOSTS: (Replace with your allowed hosts / ex: example1.com:example2.com)
    volumes:
      - ../static:/static
    ports:
      - "localhost:8000:8000"