version: '3'
services:
  db:
    image: postgres:12
    expose: 
      - 5432
  web:
    build: .
    depends_on:
      - db
    command: ["/entry/wait-for-it.sh", "db:5432", "--", "/entry/entrypoint.sh"]
    expose: 
      - 8000

