version: '3'
services:
  web:
    environment:
      DJANGO_SECRET_KEY: (Replace with your secret key)
      DJANGO_DEBUG: 'False'
      DJANGO_ALLOWED_HOSTS: (Replace with your allowed hosts / ex: example1.com:example2.com)
    volumes:
      - ../static:/static
      - ../upload:/upload
    ports:
      - "127.0.0.1:8000:8000"