# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170706_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='session',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='ProblemAttachment',
        ),
        migrations.DeleteModel(
            name='Seminar',
        ),
        migrations.DeleteModel(
            name='SeminarAttachment',
        ),
    ]
