# Generated by Django 2.1.7 on 2019-04-02 15:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="image",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location="/static/shop"), upload_to=""
            ),
        ),
    ]
