# Generated by Django 2.1.7 on 2019-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20190403_0023"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
