version: 2

jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - restore_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "ci_requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ci_requirements.txt
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "ci_requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Check
          command: |
            . venv/bin/activate
            flake8 src/
            pylint --load-plugins pylint_django --django-settings-module=plus_study.settings src/website src/problem src/seminar src/plus_study src/shop
            bandit -r src/

