version: 2

jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install bandit flake8 pylint pylint-django
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8 src/
      - run:
          name: Pylint
          command: |
            . venv/bin/activate
            pylint --load-plugins pylint_django src/website src/problem src/seminar src/plus_study
      - run:
          name: Check security
          command: |
            . venv/bin/activate
            bandit -r src/


