[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Minjae Gwon <beta.underalpha@gmail.com>"]
readme = "README.md"
packages = [{ include = "server", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.4"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.7.0"
isort = "^5.12.0"
django-stubs = "^4.2.3"
pyright = "^1.1.325"

[tool.isort]
profile = "black"

[tool.django-stubs]
django_settings_module = "study.settings"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
