# Generated by Django 2.0.6 on 2018-06-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0003_populate_attachment_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seminar",
            name="attachments",
        ),
        migrations.AlterField(
            model_name="seminarattachment",
            name="seminar",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="seminar.Seminar"
            ),
            preserve_default=False,
        ),
    ]
