# Generated by Django 2.0.6 on 2018-07-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0004_auto_20180621_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminarattachment",
            name="seminar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seminar_attachments",
                to="seminar.Seminar",
            ),
        ),
    ]
