# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170713_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('distributed_points', models.IntegerField()),
                ('breakthrough_points', models.IntegerField()),
                ('first_blood', models.CharField(blank=True, max_length=150)),
                ('hidden', models.BooleanField()),
            ],
            options={
                'verbose_name': '문제 인스턴스',
                'verbose_name_plural': '문제 인스턴스들',
            },
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('problem_instances', models.ManyToManyField(to='problem.ProblemInstance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Session')),
            ],
            options={
                'verbose_name': '문제 리스트',
                'verbose_name_plural': '문제 리스트들',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='breakthrough_points',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='distributed_points',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='points',
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='file',
            field=models.FileField(upload_to='problem/attachments'),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='solved_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
