# Generated by Django 2.0.6 on 2018-06-21 08:08

from django.db import migrations


def populate_attachment_field(apps, _):
    # noinspection PyPep8Naming
    ProblemAttachment = apps.get_model('problem', 'ProblemAttachment')

    delete_list = []

    for problem_attachment in ProblemAttachment.objects.all():
        reverse_relation = problem_attachment.old_problems
        if not reverse_relation.exists():
            delete_list.append(problem_attachment)
            continue

        problem_attachment.problem = reverse_relation.first()
        problem_attachment.save()

    for item in delete_list:
        item.delete()


def reverse_populate_attachment_field(apps, _):
    # noinspection PyPep8Naming
    ProblemAttachment = apps.get_model('problem', 'ProblemAttachment')

    for problem_attachment in ProblemAttachment.objects.all():
        problem_attachment.problem.attachments.add(problem_attachment)


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20180621_1707'),
    ]

    operations = [
        migrations.RunPython(populate_attachment_field, reverse_code=reverse_populate_attachment_field)
    ]
