# Generated by Django 2.0.6 on 2018-07-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20180621_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemattachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_attachments', to='problem.Problem'),
        ),
    ]
