# Generated by Django 2.0.7 on 2018-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20180711_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlist',
            name='notification',
            field=models.TextField(blank=True),
        ),
    ]
