# Generated by Django 2.0.7 on 2018-07-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problemlist_announcement'),
        ('problem', '0008_problemlist_notification'),
    ]

    operations = [
    ]
