name: CI

on:
  push:
    paths:
      - '*.py'

jobs:
  lint-flake8:
    runs-on: ubuntu-latest
    name: Lint (flake8)
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
