name: CI

on:
  push:
    branches:
      - "renewal/*"
  pull_request:
    branches:
      - "renewal/*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.9
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx affected -t run install
      - run: pnpm nx affected -t run format:check
      - run: pnpm nx affected -t run lint --parallel=3
